-- AlterTable
ALTER TABLE `Acervo` ADD COLUMN `altura` VARCHAR(191) NULL,
    ADD COLUMN `artista` VARCHAR(191) NULL,
    ADD COLUMN `cidadeOrigem` VARCHAR(191) NULL,
    ADD COLUMN `contextoHistorico` TEXT NULL,
    ADD COLUMN `dataProducao` VARCHAR(191) NULL,
    ADD COLUMN `doador` VARCHAR(191) NULL,
    ADD COLUMN `estadoConservacao` VARCHAR(191) NULL,
    ADD COLUMN `estadoOrigem` VARCHAR(191) NULL,
    ADD COLUMN `formaAquisicao` VARCHAR(191) NULL,
    ADD COLUMN `imagemCapa` VARCHAR(191) NULL,
    ADD COLUMN `largura` VARCHAR(191) NULL,
    ADD COLUMN `localizacao` VARCHAR(191) NULL,
    ADD COLUMN `material` VARCHAR(191) NULL,
    ADD COLUMN `nome` VARCHAR(191) NULL,
    ADD COLUMN `numeroInventario` VARCHAR(191) NULL,
    ADD COLUMN `paisOrigem` VARCHAR(191) NULL,
    ADD COLUMN `periodo` VARCHAR(191) NULL,
    ADD COLUMN `profundidade` VARCHAR(191) NULL,
    ADD COLUMN `tags` VARCHAR(191) NULL,
    ADD COLUMN `tecnica` VARCHAR(191) NULL;
